<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MotoTrack.Application\MotoTrack.Application.csproj" />
    <ProjectReference Include="..\MotoTrack.Domain\MotoTrack.Domain.csproj" />
    <ProjectReference Include="..\MotoTrack.Infrastructure\MotoTrack.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.2" />
  </ItemGroup>

</Project>
