// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotoTrack.Infrastructure.Persistence;

#nullable disable

namespace MotoTrack.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MotoTrackDbContext))]
    [Migration("20260715145738_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("MotoTrack.Domain.Models.ConfiguracionMantenimiento", b =>
                {
                    b.Property<Guid>("MotocicletaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AjusteValvulasKm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CambioAceiteKm")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("RevisionBalatasKm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RevisionCadenaKm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RevisionFiltroAireKm")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RevisionLlantasKm")
                        .HasColumnType("INTEGER");

                    b.HasKey("MotocicletaId");

                    b.ToTable("ConfiguracionesMantenimiento", (string)null);
                });

            modelBuilder.Entity("MotoTrack.Domain.Models.Gasto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("MotocicletaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MotocicletaId");

                    b.ToTable("Gastos", (string)null);
                });

            modelBuilder.Entity("MotoTrack.Domain.Models.LecturaKilometraje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kilometraje")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MotocicletaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MotocicletaId");

                    b.HasIndex("MotocicletaId", "Fecha");

                    b.ToTable("LecturasKilometraje", (string)null);
                });

            modelBuilder.Entity("MotoTrack.Domain.Models.Mantenimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("KilometrajeServicio")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MotocicletaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Taller")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fecha");

                    b.HasIndex("MotocicletaId");

                    b.ToTable("Mantenimientos", (string)null);
                });

            modelBuilder.Entity("MotoTrack.Domain.Models.Motocicleta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cilindrada")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("KilometrajeActual")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KilometrajeCompra")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroMotor")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Placas")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VIN")
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Motocicletas", (string)null);
                });

            modelBuilder.Entity("MotoTrack.Domain.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("MotoTrack.Domain.Models.ConfiguracionMantenimiento", b =>
                {
                    b.HasOne("MotoTrack.Domain.Models.Motocicleta", null)
                        .WithOne()
                        .HasForeignKey("MotoTrack.Domain.Models.ConfiguracionMantenimiento", "MotocicletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MotoTrack.Domain.Models.Gasto", b =>
                {
                    b.HasOne("MotoTrack.Domain.Models.Motocicleta", null)
                        .WithMany()
                        .HasForeignKey("MotocicletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MotoTrack.Domain.Models.LecturaKilometraje", b =>
                {
                    b.HasOne("MotoTrack.Domain.Models.Motocicleta", null)
                        .WithMany()
                        .HasForeignKey("MotocicletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MotoTrack.Domain.Models.Mantenimiento", b =>
                {
                    b.HasOne("MotoTrack.Domain.Models.Motocicleta", null)
                        .WithMany()
                        .HasForeignKey("MotocicletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MotoTrack.Domain.Models.Motocicleta", b =>
                {
                    b.HasOne("MotoTrack.Domain.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
